name: FacelessBlocks
version: '1.0-SNAPSHOT'
main: bw.development.facelessBlocks.FacelessBlocks
api-version: '1.21'
commands:
  giverecycler:
    description: Te da un bloque Reciclador.
    usage: /giverecycler
    permission: facelessblocks.admin
  clearrecyclers:
    description: Elimina todos los recicladores del servidor.
    usage: /clearrecyclers
    permission: facelessblocks.admin